apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: resource-governance-route
  namespace: resource-governance
  labels:
    app.kubernetes.io/name: resource-governance
    app.kubernetes.io/component: governance
  annotations:
    haproxy.router.openshift.io/timeout: "300s"
    haproxy.router.openshift.io/rate-limit: "100"
spec:
  # Let OpenShift generate the host automatically for different clusters
  to:
    kind: Service
    name: resource-governance-service
    weight: 100
  port:
    targetPort: http
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
